delete older build subfolders when free space is less than 7 GB

diff --git a/.github/workflows/build-MAME.yml b/.github/workflows/build-MAME.yml
--- a/.github/workflows/build-MAME.yml
+++ b/.github/workflows/build-MAME.yml
@@ -38,9 +38,14 @@ jobs:
           cat << EOF > free_some_space.sh
           #!/bin/bash
           cd "\$1"
-          find ./ -mindepth 1 -maxdepth 1 -type d -printf "%B\@\\t%p\\n" | sort -g | head -n -5 | cut -f 2- | xargs -d "\\n" -I{} -n1 -rt -- find {} -type f -not \(  -ipath "*config*" -or -iname ".stamp*" -or -iname ".br*" -or -iname ".files*" -or -iname "Makefile*" -or -iname "*autoconf*" -or -iname "*auto.conf*" -or -iname "CMakeLists*" -or -iname "libogg.la" -or -iname "libvorbis.la" \) -delete
+          while test "\$(df -BG --output=avail ./ | tail -1 | grep -o "[0-9]*" | head -1)" -lt 7 ; do
+            find ./ -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n 1 | cut -f 2- | xargs -r rm -rf
+          done
           EOF
           chmod 755 free_some_space.sh
+          
+          # DEBUG
+          cat free_some_space.sh
           
           rm -rf ./REG-LINUX ./REG-MAME-COMPILED
           git clone --branch master "https://github.com/REG-Linux/REG-Linux.git" ./REG-LINUX
@@ -54,7 +59,7 @@ jobs:
           
           # Version
           mameversion=$(cat package/emulators/mame/mame.mk | grep GroovyMAME | grep Version | cut -d " " -f 4)
-          [ "$(cat package/emulators/libretro/libretro-mame/libretro-mame.mk | grep LIBRETRO_MAME_VERSION | grep lrmame | cut -d " " -f 3 | sed s/lrmame//g | sed s/0/0\./)" != "${mameversion}" ] && echo "MAME and libretro-mame versions do not match, aborting!" && exit 1
+          [[ "$(cat package/emulators/libretro/libretro-mame/libretro-mame.mk | grep LIBRETRO_MAME_VERSION | grep lrmame | cut -d " " -f 3 | sed s/lrmame//g | sed s/0/0\./)" != "${mameversion}" ]] && echo "MAME and libretro-mame versions do not match, aborting!" && exit 1
           echo "mameversion=${mameversion}" >> "$GITHUB_OUTPUT"
           echo "mameversion=${mameversion}"
           
@@ -69,7 +74,7 @@ jobs:
           esac
           
           # After each downloaded package is extracted, delete older and keep latest 3
-          sed -i 's:(TAR_OPTIONS) -:(TAR_OPTIONS) - \&\& find \$\$(DL_DIR) -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -2 | cut -f 2- | xargs -r rm -rfv :' buildroot/package/pkg-generic.mk
+          sed -i 's:(TAR_OPTIONS) -:(TAR_OPTIONS) - \&\& find \$\$(DL_DIR) -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -2 | cut -f 2- | xargs -r rm -rf :' buildroot/package/pkg-generic.mk
           
           # Disable CCACHE and BR2_PER_PACKAGE_DIRECTORIES
           sed -i "/BR2_CCACHE/d" configs/reglinux-board.common
