Try more free space

diff --git a/.github/workflows/build-MAME.yml b/.github/workflows/build-MAME.yml
--- a/.github/workflows/build-MAME.yml
+++ b/.github/workflows/build-MAME.yml
@@ -38,15 +38,13 @@ jobs:
           cat << EOF > free_some_space.sh
           #!/bin/bash
           cd "\$1"
-          find ./ -type f -not -ipath "*mame*" -iname "*.o" -delete
-          ESCAPELOOP=0
-          while test "\$(df -BG --output=avail ./ | tail -1 | grep -o "[0-9]*" | head -1)" -lt 7 ; do
-            find ./ -mindepth 1 -maxdepth 1 -type d -not \( -iname "*headers*" -or -iname "*mame*" \) -exec du -sk -- {} \; 2>/dev/null | sort -hr | head -1 | cut -f 2- | xargs -d "\\n" -I{} -n1 -rt -- find {} -type f -not \( -ipath "*config*" -or -iname ".stamp*" -or -iname ".br*" -iname ".files*" -or -iname "Makefile*" -or -iname "*autoconf*" -or -iname "*auto.conf*" -or -iname "CMakeLists*" \) -delete
-            ((ESCAPELOOP++))
-            [[ "\$ESCAPELOOP" -lt 10 ]] || break
-          done
+          find ./ -type f -iname "*.o" -delete
+          find ./ -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -2 | cut -f 2- | xargs -d "\\n" -I{} -n1 -rt -- find {} -type f -not \( -iname ".stamp*" -or -iname ".br*" -iname ".files*" \) -delete
           EOF
           chmod 755 free_some_space.sh
+          
+          # DEBUG
+          cat free_some_space.sh
           
           rm -rf ./REG-LINUX ./REG-MAME-COMPILED
           git clone --branch master "https://github.com/REG-Linux/REG-Linux.git" ./REG-LINUX
@@ -59,11 +57,10 @@ jobs:
           CUSTOM_DIR=${GITHUB_WORKSPACE}/REG-LINUX/custom BUILDROOT_DIR=${GITHUB_WORKSPACE}/REG-LINUX/buildroot ${GITHUB_WORKSPACE}/REG-LINUX/scripts/linux/mergeToBR.sh
           
           # Version
-          mameversion="0.276"
+          mameversion=$(cat package/emulators/mame/mame.mk | grep GroovyMAME | grep Version | cut -d " " -f 4)
+          [ "$(cat package/emulators/libretro/libretro-mame/libretro-mame.mk | grep LIBRETRO_MAME_VERSION | grep lrmame | cut -d " " -f 3 | sed s/lrmame//g | sed s/0/0\./)" != "${mameversion}" ] && echo "MAME and libretro-mame versions do not match, aborting!" && exit 1
           echo "mameversion=${mameversion}" >> "$GITHUB_OUTPUT"
           echo "mameversion=${mameversion}"
-          sed -i "s/gm0275sr221d/gm0276sr221e/g" package/emulators/mame/mame.mk
-          sed -i "s/lrmame0275/lrmame0276/g" package/emulators/libretro/libretro-mame/libretro-mame.mk
           
           case ${{ matrix.platform }} in
             x86_64|x86_64_v3|asahi)
@@ -76,7 +73,7 @@ jobs:
           esac
           
           # After each downloaded package is extracted, delete older and keep latest 3
-          sed -i 's:(TAR_OPTIONS) -:(TAR_OPTIONS) - \&\& find \$\$(DL_DIR) -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -3 | cut -f 2- | xargs -r rm -rfv :' buildroot/package/pkg-generic.mk
+          sed -i 's:(TAR_OPTIONS) -:(TAR_OPTIONS) - \&\& find \$\$(DL_DIR) -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -2 | cut -f 2- | xargs -r rm -rfv :' buildroot/package/pkg-generic.mk
           
           # Disable CCACHE and BR2_PER_PACKAGE_DIRECTORIES
           sed -i "/BR2_CCACHE/d" configs/reglinux-board.common
@@ -99,11 +96,16 @@ jobs:
             CCACHE_DISABLE=1 make BR2_EXTERNAL=${GITHUB_WORKSPACE}/REG-LINUX -C ${GITHUB_WORKSPACE}/REG-LINUX/buildroot libretro-mame
             
             # DEBUG
-            find ${GITHUB_WORKSPACE}/REG-LINUX/buildroot/output/ -type d -iname '*mame*' -or -iname '*libretro*'
+            find ${GITHUB_WORKSPACE}/REG-LINUX/buildroot/ -type d -iname '*mame*' -or -iname '*libretro*'
             
             # Create package
-            cd ${GITHUB_WORKSPACE}/REG-LINUX/buildroot/output/target || exit 1
-            tar czf  "${GITHUB_WORKSPACE}/REG-MAME-COMPILED/reglinux-mame-${mameversion}-${{ matrix.platform }}.tar.gz" usr/bin/mame/ usr/lib/libretro/mame_libretro.so usr/share/mame/ usr/share/lr-mame/
+            cd ${GITHUB_WORKSPACE}/REG-LINUX/buildroot || exit 1
+            mkdir -p output/${{ matrix.platform }}/per-package/mame/target/usr/bin output/${{ matrix.platform }}/per-package/libretro-mame/target/usr/lib/libretro output/${{ matrix.platform }}/per-package/mame/target/usr/share output/${{ matrix.platform }}/per-package/libretro-mame/target/usr/share
+            mv output/target/usr/bin/mame output/${{ matrix.platform }}/per-package/mame/target/usr/bin/
+            mv output/target/usr/lib/libretro/mame_libretro.so output/${{ matrix.platform }}/per-package/libretro-mame/target/usr/lib/libretro/
+            mv output/target/usr/share/mame output/${{ matrix.platform }}/per-package/mame/target/usr/share/
+            mv output/target/usr/share/lr-mame output/${{ matrix.platform }}/per-package/libretro-mame/target/usr/share/
+            tar czf  "${GITHUB_WORKSPACE}/REG-MAME-COMPILED/reglinux-mame-${mameversion}-${{ matrix.platform }}.tar.gz" output/${{ matrix.platform }}/per-package/mame/target/usr/bin/mame/ output/${{ matrix.platform }}/per-package/libretro-mame/target/usr/lib/libretro/mame_libretro.so output/${{ matrix.platform }}/per-package/mame/target/usr/share/mame/ output/${{ matrix.platform }}/per-package/libretro-mame/target/usr/share/lr-mame/
             echo "dorelease=${{ true }}" >> "$GITHUB_OUTPUT"
           fi
 
